version: '3.9'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
  mongodb:
    image: mongo:6.0.5
    ports:
     - "27017:27017"
  neo4j:
    image: neo4j:5.6.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"